### PR TITLE
remove mysql_config's options not compatible with MariaDB

### PR DESCRIPTION
**Pull request by bigio**
Some options of the program mysql_config are not compatible with MariaDB (they have been removed), use only the options compatible both with MySQL and MariaDB

### CODE REVIEW

**Comment by mbeijen** [comment]
I understand that problem - I addressed it now in a8f66357a67c0f1595854eed877fa7a1b4a2b609 . Your suggested solution would remove command line options for the Makefile.PL - I leave that still in place while also only using mysql_config for options such as --libs.

Please let me know if this works for you, or if you still see the verbose output.

**Comment by bigio** [comment]
On 01/28/15 21:03, Michiel Beijen wrote:
> I understand that problem - I addressed it now in a8f6635 <https://github.com/perl5-dbi/DBD-mysql/commit/a8f66357a67c0f1595854eed877fa7a1b4a2b609> . Your suggested solution would remove command line options for the Makefile.PL - I leave that still in place while also only using mysql_config for options such as --libs.
> 
> Please let me know if this works for you, or if you still see the verbose output.
> 
it works, thanks.
 Cheers
  Giovanni

**Comment by dveeden** [comment]
It looks like this PR should be closed?

**Comment by bigio** [comment]
On 05/14/15 19:45, Daniël van Eeden wrote:
> It looks like this PR should be closed?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/perl5-dbi/DBD-mysql/pull/30#issuecomment-102114982>.
> 
Yes, it should be closed.
 Giovanni

**Comment by mbeijen** [comment]
Closing!

**Pull request closed without merging**
