### PR TITLE
Fixes for windows build

### PR DESCRIPTION
**Pull request by pali**

### CODE REVIEW

**Comment by mbeijen** [comment]
Hi pali, thanks, but it's still not enough: https://ci.appveyor.com/project/mbeijen/dbd-mysql-mf7me/build/1.0.117

**Comment by pali** [comment]
Err... I know, you merged it too early... Going to create new pull request and ideally wait until all tests passes.

**Comment by pali** [comment]
Can you remove this commit? Fix is in https://github.com/perl5-dbi/DBD-mysql/pull/60 see https://ci.appveyor.com/project/mbeijen/dbd-mysql-mf7me/build/1.0.113

**Comment by mbeijen** [comment]
Removed and the commits of #60 are now in master. Sorry for the bother!!

**Pull request merged**
