### PR TITLE
fix build on mariadb 10.2.12

### PR DESCRIPTION
**Pull request by jettero**
I'm aware of #218 and #219 ... I took the patches from #219 and applied them for personal use.

Then I thought, why not submit as a PR. I'm aware of #133 but that might be for a slightly different issue, and if nothing else, this PR collects #218, #219 and #133 in one place.

### CODE REVIEW

**Comment by jettero** [comment]
(the travis tests all fail because of a zerofill issue ... I made no attempt to fix that.

**Comment by pali** [comment]
But you are trying to break zerofill support... which was fixed in 4.0.42. And you are also trying to break MySQL by that check for removal mysql_skip_secure_auth.

**Comment by jettero** [comment]
I just forked form whatever develop was... I didn't break zero fill afaik. Just made dbd-mysql install.

And it's possible I broke secure auth, but lemme ask you this:  Which is better?

1) can't install dbd-mysql; I guess perl is dead
2) I can install dbd-mysql, wahoo; oh, some little things broke on the side

**Comment by jettero** [comment]
Ahh, I see the zero fill  problem. Fixing.

**Comment by jettero** [comment]
zero fill seems to work again (rebased 4.043); I'll look at the secure auth in a bit.

**Comment by jettero** [comment]
I'd also like to take a comment slot to say: man travis-ci is awesome.

**Comment by pali** [comment]
With your last change you are going to break MariaDB 10.1... look at comments around ifdefs which you changed...

**Comment by jettero** [comment]
I removed most of the changes the patches introduced. It's pretty much just an #if around the ->reconnect now.

**Comment by pali** [comment]
Now https://github.com/gooddata/DBD-MariaDB repository contains patches for MariaDB 10.2/10.3.

**Comment by mbeijen** [comment]
Fixed in 0b1884f4153d3de0a91bae4d3b3cc1771ffdf4f3

**Pull request closed without merging**
