### PR TITLE
Fix compilation of embedded mysql server

### PR DESCRIPTION
**Pull request by pali**
Compilation of embedded mysql server is working. Embedded tests are passing too. Now travis-ci run tests for both normal and embedded server.

### CODE REVIEW

**Comment by pali** [comment]
Hm... t/manifest.t is failing :-( Looks like it should ignore mysqlEmb directory.

**Comment by mbeijen** [comment]
I fixed `t/manifest.t` by adding e932e1f7f6d3a179200195614acfd711a2d5fc9a to master.

**Comment by mbeijen** [comment]
I've *never* worked with the embedded server. I think the complaint about the missing table is because you should first call `mysql_library_init`. 

http://dev.mysql.com/doc/refman/5.7/en/libmysqld-example.html

On the other hand, embedded use has been broken for a LONG time. Also, the manual states:

> **Note**
> The libmysqld embedded server library is deprecated as of MySQL 5.7.17 and will be removed in a future version of MySQL.

(ref: http://dev.mysql.com/doc/refman/5.7/en/libmysqld.html)
And, of course, sqlite!

So while I think it is great if we can get it fixed, another option might be to rip the code out altogether. Let me know what you think!

**Comment by pali** [comment]
Current implementation is working. We just passed unrecognized server parameter --skip-dbd in tests. Which caused that problem "Embedded server was not started".

Warning message "mysql_embedded: Table 'mysql.plugin' doesn't exist" is OK here. We just do not have plugin support but that does not matter for simple tests.

**Pull request merged**
